/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects.$projectId.index'
import { Route as ProjectsProjectIdWorkflowRouteImport } from './routes/projects.$projectId.workflow'
import { Route as ProjectsProjectIdTurnoverRouteImport } from './routes/projects.$projectId.turnover'
import { Route as ProjectsProjectIdSystemsRouteImport } from './routes/projects.$projectId.systems'
import { Route as ProjectsProjectIdPunchRouteImport } from './routes/projects.$projectId.punch'
import { Route as ProjectsProjectIdPreservationRouteImport } from './routes/projects.$projectId.preservation'
import { Route as ProjectsProjectIdMcRouteImport } from './routes/projects.$projectId.mc'
import { Route as ProjectsProjectIdDocumentsRouteImport } from './routes/projects.$projectId.documents'
import { Route as ProjectsProjectIdCommissioningRouteImport } from './routes/projects.$projectId.commissioning'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdWorkflowRoute =
  ProjectsProjectIdWorkflowRouteImport.update({
    id: '/workflow',
    path: '/workflow',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdTurnoverRoute =
  ProjectsProjectIdTurnoverRouteImport.update({
    id: '/turnover',
    path: '/turnover',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdSystemsRoute =
  ProjectsProjectIdSystemsRouteImport.update({
    id: '/systems',
    path: '/systems',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdPunchRoute = ProjectsProjectIdPunchRouteImport.update({
  id: '/punch',
  path: '/punch',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdPreservationRoute =
  ProjectsProjectIdPreservationRouteImport.update({
    id: '/preservation',
    path: '/preservation',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdMcRoute = ProjectsProjectIdMcRouteImport.update({
  id: '/mc',
  path: '/mc',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdDocumentsRoute =
  ProjectsProjectIdDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdCommissioningRoute =
  ProjectsProjectIdCommissioningRouteImport.update({
    id: '/commissioning',
    path: '/commissioning',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/commissioning': typeof ProjectsProjectIdCommissioningRoute
  '/projects/$projectId/documents': typeof ProjectsProjectIdDocumentsRoute
  '/projects/$projectId/mc': typeof ProjectsProjectIdMcRoute
  '/projects/$projectId/preservation': typeof ProjectsProjectIdPreservationRoute
  '/projects/$projectId/punch': typeof ProjectsProjectIdPunchRoute
  '/projects/$projectId/systems': typeof ProjectsProjectIdSystemsRoute
  '/projects/$projectId/turnover': typeof ProjectsProjectIdTurnoverRoute
  '/projects/$projectId/workflow': typeof ProjectsProjectIdWorkflowRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$projectId/commissioning': typeof ProjectsProjectIdCommissioningRoute
  '/projects/$projectId/documents': typeof ProjectsProjectIdDocumentsRoute
  '/projects/$projectId/mc': typeof ProjectsProjectIdMcRoute
  '/projects/$projectId/preservation': typeof ProjectsProjectIdPreservationRoute
  '/projects/$projectId/punch': typeof ProjectsProjectIdPunchRoute
  '/projects/$projectId/systems': typeof ProjectsProjectIdSystemsRoute
  '/projects/$projectId/turnover': typeof ProjectsProjectIdTurnoverRoute
  '/projects/$projectId/workflow': typeof ProjectsProjectIdWorkflowRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/commissioning': typeof ProjectsProjectIdCommissioningRoute
  '/projects/$projectId/documents': typeof ProjectsProjectIdDocumentsRoute
  '/projects/$projectId/mc': typeof ProjectsProjectIdMcRoute
  '/projects/$projectId/preservation': typeof ProjectsProjectIdPreservationRoute
  '/projects/$projectId/punch': typeof ProjectsProjectIdPunchRoute
  '/projects/$projectId/systems': typeof ProjectsProjectIdSystemsRoute
  '/projects/$projectId/turnover': typeof ProjectsProjectIdTurnoverRoute
  '/projects/$projectId/workflow': typeof ProjectsProjectIdWorkflowRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/projects/$projectId'
    | '/projects/'
    | '/projects/$projectId/commissioning'
    | '/projects/$projectId/documents'
    | '/projects/$projectId/mc'
    | '/projects/$projectId/preservation'
    | '/projects/$projectId/punch'
    | '/projects/$projectId/systems'
    | '/projects/$projectId/turnover'
    | '/projects/$projectId/workflow'
    | '/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/projects'
    | '/projects/$projectId/commissioning'
    | '/projects/$projectId/documents'
    | '/projects/$projectId/mc'
    | '/projects/$projectId/preservation'
    | '/projects/$projectId/punch'
    | '/projects/$projectId/systems'
    | '/projects/$projectId/turnover'
    | '/projects/$projectId/workflow'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/projects/$projectId'
    | '/projects/'
    | '/projects/$projectId/commissioning'
    | '/projects/$projectId/documents'
    | '/projects/$projectId/mc'
    | '/projects/$projectId/preservation'
    | '/projects/$projectId/punch'
    | '/projects/$projectId/systems'
    | '/projects/$projectId/turnover'
    | '/projects/$projectId/workflow'
    | '/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/workflow': {
      id: '/projects/$projectId/workflow'
      path: '/workflow'
      fullPath: '/projects/$projectId/workflow'
      preLoaderRoute: typeof ProjectsProjectIdWorkflowRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/turnover': {
      id: '/projects/$projectId/turnover'
      path: '/turnover'
      fullPath: '/projects/$projectId/turnover'
      preLoaderRoute: typeof ProjectsProjectIdTurnoverRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/systems': {
      id: '/projects/$projectId/systems'
      path: '/systems'
      fullPath: '/projects/$projectId/systems'
      preLoaderRoute: typeof ProjectsProjectIdSystemsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/punch': {
      id: '/projects/$projectId/punch'
      path: '/punch'
      fullPath: '/projects/$projectId/punch'
      preLoaderRoute: typeof ProjectsProjectIdPunchRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/preservation': {
      id: '/projects/$projectId/preservation'
      path: '/preservation'
      fullPath: '/projects/$projectId/preservation'
      preLoaderRoute: typeof ProjectsProjectIdPreservationRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/mc': {
      id: '/projects/$projectId/mc'
      path: '/mc'
      fullPath: '/projects/$projectId/mc'
      preLoaderRoute: typeof ProjectsProjectIdMcRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/documents': {
      id: '/projects/$projectId/documents'
      path: '/documents'
      fullPath: '/projects/$projectId/documents'
      preLoaderRoute: typeof ProjectsProjectIdDocumentsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/commissioning': {
      id: '/projects/$projectId/commissioning'
      path: '/commissioning'
      fullPath: '/projects/$projectId/commissioning'
      preLoaderRoute: typeof ProjectsProjectIdCommissioningRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
  }
}

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdCommissioningRoute: typeof ProjectsProjectIdCommissioningRoute
  ProjectsProjectIdDocumentsRoute: typeof ProjectsProjectIdDocumentsRoute
  ProjectsProjectIdMcRoute: typeof ProjectsProjectIdMcRoute
  ProjectsProjectIdPreservationRoute: typeof ProjectsProjectIdPreservationRoute
  ProjectsProjectIdPunchRoute: typeof ProjectsProjectIdPunchRoute
  ProjectsProjectIdSystemsRoute: typeof ProjectsProjectIdSystemsRoute
  ProjectsProjectIdTurnoverRoute: typeof ProjectsProjectIdTurnoverRoute
  ProjectsProjectIdWorkflowRoute: typeof ProjectsProjectIdWorkflowRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdCommissioningRoute: ProjectsProjectIdCommissioningRoute,
  ProjectsProjectIdDocumentsRoute: ProjectsProjectIdDocumentsRoute,
  ProjectsProjectIdMcRoute: ProjectsProjectIdMcRoute,
  ProjectsProjectIdPreservationRoute: ProjectsProjectIdPreservationRoute,
  ProjectsProjectIdPunchRoute: ProjectsProjectIdPunchRoute,
  ProjectsProjectIdSystemsRoute: ProjectsProjectIdSystemsRoute,
  ProjectsProjectIdTurnoverRoute: ProjectsProjectIdTurnoverRoute,
  ProjectsProjectIdWorkflowRoute: ProjectsProjectIdWorkflowRoute,
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
