/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects.$projectId.index'
import { Route as ProjectsProjectIdSystemsRouteImport } from './routes/projects.$projectId.systems'
import { Route as ProjectsProjectIdPunchRouteImport } from './routes/projects.$projectId.punch'
import { Route as ProjectsProjectIdMcRouteImport } from './routes/projects.$projectId.mc'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdSystemsRoute =
  ProjectsProjectIdSystemsRouteImport.update({
    id: '/systems',
    path: '/systems',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdPunchRoute = ProjectsProjectIdPunchRouteImport.update({
  id: '/punch',
  path: '/punch',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdMcRoute = ProjectsProjectIdMcRouteImport.update({
  id: '/mc',
  path: '/mc',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/$projectId/mc': typeof ProjectsProjectIdMcRoute
  '/projects/$projectId/punch': typeof ProjectsProjectIdPunchRoute
  '/projects/$projectId/systems': typeof ProjectsProjectIdSystemsRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/projects/$projectId/mc': typeof ProjectsProjectIdMcRoute
  '/projects/$projectId/punch': typeof ProjectsProjectIdPunchRoute
  '/projects/$projectId/systems': typeof ProjectsProjectIdSystemsRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/$projectId/mc': typeof ProjectsProjectIdMcRoute
  '/projects/$projectId/punch': typeof ProjectsProjectIdPunchRoute
  '/projects/$projectId/systems': typeof ProjectsProjectIdSystemsRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects'
    | '/projects/$projectId'
    | '/projects/$projectId/mc'
    | '/projects/$projectId/punch'
    | '/projects/$projectId/systems'
    | '/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projects'
    | '/projects/$projectId/mc'
    | '/projects/$projectId/punch'
    | '/projects/$projectId/systems'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/projects'
    | '/projects/$projectId'
    | '/projects/$projectId/mc'
    | '/projects/$projectId/punch'
    | '/projects/$projectId/systems'
    | '/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/systems': {
      id: '/projects/$projectId/systems'
      path: '/systems'
      fullPath: '/projects/$projectId/systems'
      preLoaderRoute: typeof ProjectsProjectIdSystemsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/punch': {
      id: '/projects/$projectId/punch'
      path: '/punch'
      fullPath: '/projects/$projectId/punch'
      preLoaderRoute: typeof ProjectsProjectIdPunchRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/mc': {
      id: '/projects/$projectId/mc'
      path: '/mc'
      fullPath: '/projects/$projectId/mc'
      preLoaderRoute: typeof ProjectsProjectIdMcRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
  }
}

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdMcRoute: typeof ProjectsProjectIdMcRoute
  ProjectsProjectIdPunchRoute: typeof ProjectsProjectIdPunchRoute
  ProjectsProjectIdSystemsRoute: typeof ProjectsProjectIdSystemsRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdMcRoute: ProjectsProjectIdMcRoute,
  ProjectsProjectIdPunchRoute: ProjectsProjectIdPunchRoute,
  ProjectsProjectIdSystemsRoute: ProjectsProjectIdSystemsRoute,
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
